# Generated by Django 3.1.4 on 2021-02-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210219_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.address'),
        ),
    ]
