# Generated by Django 3.1.4 on 2021-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='date',
        ),
        migrations.AddField(
            model_name='factor',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
