# Generated by Django 3.1.4 on 2021-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210219_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='timeOfDeliveringToThePost',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
