# Generated by Django 3.1.4 on 2021-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_factor_timeofdeliveringtothepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='postCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
