# Generated by Django 3.1.4 on 2021-02-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210219_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Fa_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Fa_last_name',
            new_name='last_name',
        ),
    ]
