# Generated by Django 3.1.4 on 2021-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210220_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Guilan', 'Guilan'), ('Fars', 'Fars'), ('Tehran', 'Tehran'), ('Esfehan', 'Esfehan'), ('Markazi', 'Markazi'), ('Hamedan', 'Hamedan')], max_length=500),
        ),
    ]
