# Generated by Django 3.1.4 on 2021-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210222_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='staticNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
