# Generated by Django 3.1.4 on 2021-02-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210222_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='review_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='review_title',
        ),
    ]
